# SonarQube configuration
sonar.host.url=https://sonarqube.home.erenkrmt.org
sonar.token=squ_ae3508ee8ada710ddcf61c8f0b023c338bd2e491

# SonarCloud project configuration
sonar.projectKey=Erenkrmt_dc-manager
sonar.organization=erenkrmt
sonar.projectName=dc-trade-api
sonar.projectVersion=3.2.0

# Sources
sonar.sources=src/,main.py
sonar.language=py

# Exclusions
sonar.exclusions=**/__pycache__/**,**/tests/**,**/data/**,**/scripts/**,**/alembic/**

# Encoding
sonar.sourceEncoding=UTF-8

# Python version
sonar.python.version=3.14
